[package]
name = "compact_cert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_merkle = "1.4"
rand = "0.8"
elliptic_curve = "0.13.8"